all: serve
# https://cli.vuejs.org/zh/guide/prototyping.html
serve:
	vue serve hello.vue

build:
	vue build hello.vue

lib:
	vue build hello.vue --target lib --name Hello --dest lib

clean:
	rm -rf dist node_modules lib

